### ISSUE TITLE
[BUG] - ERROR by EZM (Uploaded on YouTube)

### ISSUE THREAD

**Issue by FinalBiologic** [expung3d/Enhanced-Zeus-Modules#37] opened 2024-11-07 17:34 UTC
**Describe the bug**
**Error:** _https://youtu.be/9sCiRLm1__0?si=vQJpBWYwAQvCv44Y_

**To Reproduce**
**all settings of mission:** _https://youtu.be/WC6uVnrgpzw?si=5ML5bc5Q9kprcjQ6_

**Expected behavior**
A functioning Zeus as in the Multiplyer test

**Screenshots**
1 video in which you can see all my mission settings and descrition.ext etc and 1 video that describes the complete bug in video form because it is too long to explain and my English is not the best in this respect

**Additional context**
Please contact me, a Google search of my name is enough to get all contact information. Discord,Steam,BIA Forum,... Everywhere the same name: FinalBiologic

**Comment by OPOP15** [comment] 2024-11-10 04:12
i have the same problem but i fnd out why
you need to link one module on the zeus

![螢幕擷取畫面 2024-11-10 121147](https://github.com/user-attachments/assets/b153d2bd-e119-4d7d-a4a1-9241c1d5fae0)
![圖片](https://github.com/user-attachments/assets/1c24cdd3-99b1-4de6-8f56-96ad93747ee0)

**Comment by expung3d** [comment] 2024-11-10 17:54
This is caused by the anti-cheat feature for Public Zeus. It prevents people from accessing Zeus outside of the two default curators on the 16/48+2 missions. The vehicle variable name for the curators are bis_curator and bis_curator_1. If the curator's vehicle var name is not equal to one of those, it deletes the curator. 

I'll change it to where when EZM is ran it will allow any curators already spawned in the mission to be used. The update should be out in the next week officially, or you can use it on the dev branch once I update it. Be aware though that the dev branch is removing a lot of the EZM factions to make them optional, if you intend to use them I would wait for the official release.

**Comment by expung3d** [comment] 2024-11-12 07:51
Fixed with version 2.0.22

**Closed by expung3d** 2024-11-12 07:51 UTC
Labels: bug
